import React, { useMemo, useState } from 'react';
import { Alert, Linking, Modal, Platform, Pressable, SafeAreaView, ScrollView, StatusBar, StyleSheet, Switch, Text, TextInput, View } from 'react-native';
import { LinearGradient } from 'expo-linear-gradient';
import { Ionicons } from '@expo/vector-icons';

const C={navy:'#10283F',green:'#00A982',dark:'#008367',mint:'#DFF8EF',bg:'#F4F8F8',ink:'#173144',muted:'#6C7E89',line:'#DCE8EA',white:'#FFF',blue:'#E8F4FF',gold:'#FFF3D8'};
const tests=[
 {id:1,name:'Hemograma completo',prep:'Sin ayuno',time:'24 horas',price:45000},
 {id:2,name:'Perfil lipídico',prep:'Ayuno de 8–12 horas',time:'24 horas',price:69000},
 {id:3,name:'Perfil tiroideo',prep:'Consultar preparación',time:'48 horas',price:128000},
 {id:4,name:'Vitamina D',prep:'Sin ayuno',time:'48 horas',price:118000},
 {id:5,name:'Glucosa en ayunas',prep:'Ayuno de 8 horas',time:'24 horas',price:33000}
];
const results=[
 {title:'Perfil metabólico integral',code:'AV-260831',date:'31 ago 2026',status:'Disponible',tone:'green'},
 {title:'Vitamina D + Ferritina',code:'AV-260908',date:'8 sep 2026',status:'En análisis',tone:'gold'},
 {title:'Perfil lipídico + Hemograma',code:'AV-260912',date:'12 sep 2026',status:'Programada',tone:'blue'}
];
const events=[
 {day:'19',month:'SEP',tag:'JORNADA AV',title:'Chequeo preventivo familiar',place:'Suba, Bogotá',time:'7:00 a. m. – 12:00 m.',text:'Hemograma, glucosa y perfil lipídico para toda la familia.'},
 {day:'23',month:'SEP',tag:'VIRTUAL',title:'Cómo prepararte para tus exámenes',place:'En línea',time:'6:30 p. m.',text:'Encuentro educativo con espacio de preguntas.'},
 {day:'26',month:'SEP',tag:'COMUNIDAD',title:'Ruta de bienestar cardiovascular',place:'Chía, Cundinamarca',time:'8:00 a. m.',text:'Actividad preventiva y orientación general.'}
];
const money=n=>'$'+Math.round(n).toLocaleString('es-CO');

function Icon({name,onPress,bg=C.white,color=C.navy}){return <Pressable onPress={onPress} style={[s.icon,{backgroundColor:bg}]}><Ionicons name={name} size={21} color={color}/></Pressable>}
function Pill({children,tone='green'}){const p=tone==='gold'?[C.gold,'#89640E']:tone==='blue'?[C.blue,'#377AA3']:[C.mint,C.dark];return <View style={[s.pill,{backgroundColor:p[0]}]}><Text style={[s.pillText,{color:p[1]}]}>{children}</Text></View>}
function Header({title,subtitle,bell=true}){return <View style={s.header}><View><Text style={s.brand}>ANDREA VALLEJO</Text><Text style={s.h1}>{title}</Text>{subtitle&&<Text style={s.sub}>{subtitle}</Text>}</View>{bell&&<Icon name="notifications-outline" onPress={()=>Alert.alert('Notificaciones','No tienes nuevas notificaciones.')}/>}</View>}
function Button({children,onPress,disabled=false,outline=false}){return <Pressable disabled={disabled} onPress={onPress} style={[s.button,outline&&s.buttonOutline,disabled&&{opacity:.4}]}><Text style={[s.buttonText,outline&&{color:C.dark}]}>{children}</Text><Ionicons name="arrow-forward" size={18} color={outline?C.dark:C.white}/></Pressable>}

function Home({go,open}){
 return <ScrollView contentContainerStyle={s.screen} showsVerticalScrollIndicator={false}>
  <Header title="Hola, María Camila 👋" subtitle="¿Qué necesitas hoy?"/>
  <LinearGradient colors={[C.navy,'#215C62']} style={s.member}>
   <View style={s.between}><View style={s.memberHead}><View style={s.memberIcon}><Ionicons name="sparkles" size={21} color="#65EBC5"/></View><View><Text style={s.lightOver}>TU NIVEL ACTUAL</Text><Text style={s.memberTitle}>Preferente</Text></View></View><Pill>15% AHORRO</Pill></View>
   <Text style={s.memberCopy}>Te faltan 2 tomas para alcanzar Premium y ahorrar hasta 22%.</Text><View style={s.progress}><View style={s.progressFill}/></View>
   <Pressable onPress={()=>go('beneficios')}><Text style={s.lightLink}>Ver mis beneficios  →</Text></Pressable>
  </LinearGradient>
  <Text style={s.section}>Acciones rápidas</Text>
  <View style={s.grid}>
   <Quick icon="medical" title="Solicitar toma" copy="En casa u oficina" primary onPress={()=>go('solicitar')}/>
   <Quick icon="document-text-outline" title="Mis resultados" copy="Estado y descarga" onPress={()=>go('resultados')}/>
   <Quick icon="chatbubble-ellipses-outline" title="Hablar con alguien" copy="Orientación profesional" onPress={()=>open('contacto')}/>
   <Quick icon="videocam-outline" title="Reunión virtual" copy="Familias y empresas" onPress={()=>open('reunion')}/>
  </View>
  <Text style={s.section}>Próxima visita</Text>
  <View style={s.card}><View style={s.between}><Pill>CONFIRMADA</Pill><Text style={s.order}>AV-260912</Text></View>
   <View style={s.visit}><DateBox day="12" month="SEP"/><View style={{flex:1}}><Text style={s.cardTitle}>Perfil lipídico + Hemograma</Text><Meta icon="time-outline">7:30 a. m. – 8:00 a. m.</Meta><Meta icon="location-outline">Calle 127 # 19–42</Meta></View></View>
   <View style={s.line}/><View style={s.between}><View style={s.prof}><View style={s.avatar}><Text style={s.avatarText}>AV</Text></View><View><Text style={s.caption}>Profesional asignada</Text><Text style={s.strong}>Andrea Vallejo</Text></View></View><Icon name="call-outline" bg={C.mint} color={C.dark} onPress={()=>open('contacto')}/></View>
   <View style={s.prep}><Ionicons name="restaurant-outline" size={19} color="#8A6612"/><Text style={s.prepText}><Text style={{fontWeight:'800'}}>Recuerda: </Text>ayuno de 8 a 12 horas. Puedes tomar agua.</Text></View>
  </View>
  <View style={s.between}><Text style={s.section}>Próximas jornadas</Text><Pressable onPress={()=>go('agenda')}><Text style={s.link}>Ver todas</Text></Pressable></View>
  <Pressable style={s.eventPreview} onPress={()=>go('agenda')}><DateBox day="19" month="SEP"/><View style={{flex:1}}><Text style={s.tag}>JORNADA AV</Text><Text style={s.strong}>Chequeo preventivo familiar</Text><Text style={s.meta}>Suba, Bogotá · 7:00 a. m.</Text></View><Ionicons name="chevron-forward" size={20} color={C.muted}/></Pressable>
  <Text style={s.demo}>Contenido demostrativo. Confirma fechas y disponibilidad antes de publicar.</Text>
 </ScrollView>
}
function Quick({icon,title,copy,onPress,primary}){return <Pressable onPress={onPress} style={[s.quick,primary&&{backgroundColor:C.green,borderColor:C.green}]}><View style={[s.quickIcon,{backgroundColor:primary?'rgba(255,255,255,.18)':C.mint}]}><Ionicons name={icon} size={22} color={primary?C.white:C.dark}/></View><Text style={[s.quickTitle,primary&&{color:C.white}]}>{title}</Text><Text style={[s.quickCopy,primary&&{color:'#D7FFF3'}]}>{copy}</Text></Pressable>}
function DateBox({day,month}){return <View style={s.date}><Text style={s.dateDay}>{day}</Text><Text style={s.dateMonth}>{month}</Text></View>}
function Meta({icon,children}){return <Text style={s.meta}><Ionicons name={icon} size={14}/>  {children}</Text>}

function Request({open}){
 const [selected,setSelected]=useState([]),[query,setQuery]=useState('');
 const subtotal=useMemo(()=>tests.filter(t=>selected.includes(t.id)).reduce((a,t)=>a+t.price,0),[selected]);
 const toggle=id=>setSelected(x=>x.includes(id)?x.filter(n=>n!==id):[...x,id]);
 return <ScrollView contentContainerStyle={s.screen} showsVerticalScrollIndicator={false}><Header title="Solicitar toma" subtitle="Selecciona las pruebas que necesitas"/>
  <View style={s.steps}>{[1,2,3].map((n,i)=><React.Fragment key={n}><View style={[s.step,i===0&&s.stepActive]}><Text style={[s.stepText,i===0&&{color:C.white}]}>{n}</Text></View>{i<2&&<View style={s.stepLine}/>}</React.Fragment>)}</View>
  <View style={s.search}><Ionicons name="search" size={19} color={C.muted}/><TextInput value={query} onChangeText={setQuery} placeholder="Hemograma, tiroides, vitamina D…" placeholderTextColor="#93A1A8" style={s.searchInput}/></View>
  <View style={s.card}>{tests.filter(t=>t.name.toLowerCase().includes(query.toLowerCase())).map((t,i)=><Pressable key={t.id} onPress={()=>toggle(t.id)} style={[s.test,i>0&&s.topLine]}><View style={[s.check,selected.includes(t.id)&&s.checked]}>{selected.includes(t.id)&&<Ionicons name="checkmark" size={15} color={C.white}/>}</View><View style={{flex:1}}><Text style={s.strong}>{t.name}</Text><Text style={s.caption}>{t.prep} · {t.time}</Text></View><Text style={s.testPrice}>{money(t.price)}</Text></Pressable>)}</View>
  {!!selected.length&&<View style={s.quote}><Row label="Subtotal" value={money(subtotal)}/><Row label="Beneficio Preferente" value={'− '+money(subtotal*.15)} green/><View style={s.line}/><View style={s.between}><Text style={s.totalLabel}>Total estimado</Text><Text style={s.total}>{money(subtotal*.85)}</Text></View><Text style={s.caption}>El domicilio se calcula según la ubicación.</Text></View>}
  <Button disabled={!selected.length} onPress={()=>open('ubicacion')}>Continuar con ubicación</Button>
 </ScrollView>
}
function Row({label,value,green}){return <View style={s.between}><Text style={[s.rowText,green&&{color:C.dark}]}>{label}</Text><Text style={[s.rowValue,green&&{color:C.dark}]}>{value}</Text></View>}

function Results({open}){return <ScrollView contentContainerStyle={s.screen} showsVerticalScrollIndicator={false}><Header title="Mis resultados" subtitle="Seguimiento seguro de tus muestras"/><View style={s.search}><Ionicons name="search" size={19} color={C.muted}/><TextInput placeholder="Buscar por prueba u orden…" placeholderTextColor="#93A1A8" style={s.searchInput}/></View>
 {results.map((r,i)=><View style={s.result} key={r.code}><View style={s.between}><Pill tone={r.tone}>{r.status.toUpperCase()}</Pill><Text style={s.order}>{r.code}</Text></View><Text style={s.resultTitle}>{r.title}</Text><Text style={s.meta}>Toma: {r.date}</Text>{i===1&&<><View style={s.miniProgress}><View style={s.miniDone}/></View><Text style={s.caption}>Entrega estimada: 11 sep, antes de las 6:00 p. m.</Text></>}<View style={s.line}/>{i===0?<View style={s.actionRow}><Pressable style={s.darkButton} onPress={()=>Alert.alert('Descarga simulada','Este demo no contiene datos clínicos reales.')}><Ionicons name="download-outline" size={17} color={C.white}/><Text style={s.darkText}>Descargar PDF</Text></Pressable><Icon name="chatbubble-outline" onPress={()=>open('contacto')}/></View>:<Pressable onPress={()=>open(i===2?'preparacion':'notificacion')}><Text style={s.link}>{i===2?'Ver preparación':'Recibir notificación'}</Text></Pressable>}</View>)}
 <View style={s.privacy}><Ionicons name="shield-checkmark-outline" size={23} color="#377AA3"/><Text style={s.privacyText}><Text style={{fontWeight:'800'}}>Tus datos clínicos son privados. </Text>Este demo no almacena información médica real.</Text></View>
 </ScrollView>}

function Benefits(){
 const [tier,setTier]=useState('Preferente'),rate={Esencial:0,Preferente:.15,Premium:.22}[tier];
 return <ScrollView contentContainerStyle={s.screen} showsVerticalScrollIndicator={false}><Header title="Precios y beneficios" subtitle="Tu constancia se convierte en ahorro"/><View style={s.segment}>{['Esencial','Preferente','Premium'].map(x=><Pressable key={x} onPress={()=>setTier(x)} style={[s.segmentItem,tier===x&&s.segmentActive]}><Text style={[s.segmentText,tier===x&&s.segmentTextActive]}>{x}{x==='Preferente'?' · Tú':''}</Text></Pressable>)}</View>
 <LinearGradient colors={[C.navy,'#215C62']} style={s.saving}><Ionicons name="sparkles" size={24} color="#63E6C0"/><Text style={s.lightOver}>NIVEL {tier.toUpperCase()}</Text><Text style={s.savingNumber}>{Math.round(rate*100)}%</Text><Text style={s.savingCopy}>de ahorro en pruebas seleccionadas</Text></LinearGradient>
 <Text style={s.section}>Precios estimados</Text><View style={s.card}>{tests.slice(0,4).map((t,i)=><View key={t.id} style={[s.priceRow,i>0&&s.topLine]}><View style={{flex:1}}><Text style={s.strong}>{t.name}</Text><Text style={s.basePrice}>{money(t.price)}</Text></View><View style={{alignItems:'flex-end'}}><Text style={s.memberPrice}>{money(t.price*(1-rate))}</Text><Text style={s.caption}>Tu precio</Text></View></View>)}</View><Text style={s.demo}>Valores demostrativos en pesos colombianos. No constituyen una oferta comercial.</Text>
 </ScrollView>
}

function Agenda({open}){
 const [filter,setFilter]=useState('Todos');
 return <ScrollView contentContainerStyle={s.screen} showsVerticalScrollIndicator={false}><Header title="Agenda de salud" subtitle="Bogotá y Cundinamarca"/><ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={s.filters}>{['Todos','Bogotá','Cundinamarca','Virtual'].map(x=><Pressable key={x} onPress={()=>setFilter(x)} style={[s.filter,filter===x&&s.filterActive]}><Text style={[s.filterText,filter===x&&{color:C.white}]}>{x}</Text></Pressable>)}</ScrollView>
 {events.map((e,i)=><View key={e.title} style={s.agenda}><View style={s.between}><DateBox day={e.day} month={e.month}/><Pill tone={i===1?'blue':'green'}>{e.tag}</Pill></View><Text style={s.agendaTitle}>{e.title}</Text><Text style={s.agendaCopy}>{e.text}</Text><Meta icon={i===1?'videocam-outline':'location-outline'}>{e.place}</Meta><Meta icon="time-outline">{e.time}</Meta><Pressable style={s.reserve} onPress={()=>open('evento')}><Text style={s.reserveText}>{i===0?'Reservar cupo':'Registrar interés'}</Text><Ionicons name="arrow-forward" size={17} color={C.dark}/></Pressable></View>)}<Button outline onPress={()=>open('reunion')}>Proponer jornada empresarial</Button><Text style={s.demo}>Agenda ilustrativa. Cada evento debe verificarse antes de publicarse.</Text>
 </ScrollView>
}

function Profile({open}){
 const [notify,setNotify]=useState(true);
 return <ScrollView contentContainerStyle={s.screen} showsVerticalScrollIndicator={false}><Header title="Mi cuenta" subtitle="Información y preferencias" bell={false}/><View style={s.profileHero}><View style={s.bigAvatar}><Text style={s.bigAvatarText}>MC</Text></View><Text style={s.profileName}>María Camila Rodríguez</Text><Text style={s.meta}>Paciente Preferente · Bogotá</Text></View><View style={s.card}><Menu icon="person-outline" text="Datos personales" onPress={()=>open('perfil')}/><Menu icon="location-outline" text="Mis direcciones" onPress={()=>open('direcciones')} top/><Menu icon="people-outline" text="Grupo familiar" onPress={()=>open('familia')} top/><View style={[s.menu,s.topLine]}><Ionicons name="notifications-outline" size={21} color={C.dark}/><Text style={s.menuText}>Recordatorios</Text><Switch value={notify} onValueChange={setNotify} trackColor={{true:C.green}}/></View></View><Pressable style={s.website} onPress={()=>Linking.openURL('https://andreavallejo.com.co')}><Ionicons name="globe-outline" size={21} color={C.white}/><Text style={s.websiteText}>Visitar andreavallejo.com.co</Text><Ionicons name="open-outline" size={18} color={C.white}/></Pressable><Text style={s.version}>AndreaVallejo para iOS · Demo v0.1</Text></ScrollView>
}
function Menu({icon,text,onPress,top}){return <Pressable onPress={onPress} style={[s.menu,top&&s.topLine]}><Ionicons name={icon} size={21} color={C.dark}/><Text style={s.menuText}>{text}</Text><Ionicons name="chevron-forward" size={18} color={C.muted}/></Pressable>}

function Sheet({type,close}){
 const configs={contacto:['Habla con un profesional','Orientación sobre preparación, cobertura, servicios o cotizaciones.'],reunion:['Agendar reunión virtual','Para convenios empresariales, jornadas de salud, IPS y planes familiares.'],ubicacion:['Ubicación y horario','Indica dónde y cuándo prefieres recibir la visita.'],evento:['Reserva tu cupo','Registra tu interés y recibe confirmación por WhatsApp.'],preparacion:['Antes de tu toma','Ayuno de 8 a 12 horas. Puedes tomar agua y no debes suspender medicamentos sin indicación médica.'],notificacion:['Avisarme cuando esté listo','Recibirás una notificación cuando el informe esté disponible.'],perfil:['Datos personales','Aquí podrás actualizar tus datos de contacto de forma segura.'],direcciones:['Mis direcciones','Guarda casa, oficina y direcciones familiares.'],familia:['Grupo familiar','Gestiona perfiles autorizados para solicitudes familiares.']};
 const x=configs[type]||['Información','Función demostrativa.'],form=['contacto','reunion','ubicacion','evento'].includes(type);
 const done=()=>{close();setTimeout(()=>Alert.alert('Solicitud registrada','Esta interacción es demostrativa.'),200)};
 return <Modal transparent animationType="slide" onRequestClose={close}><Pressable style={s.backdrop} onPress={close}/><View style={s.sheet}><View style={s.handle}/><View style={s.between}><View style={{flex:1}}><Text style={s.sheetTitle}>{x[0]}</Text><Text style={s.sheetCopy}>{x[1]}</Text></View><Icon name="close" bg={C.bg} onPress={close}/></View>{form&&<View style={s.form}><Text style={s.label}>{type==='ubicacion'?'Dirección':'Nombre completo'}</Text><TextInput style={s.input} placeholder={type==='ubicacion'?'Dirección completa':'Tu nombre'} placeholderTextColor="#98A5AB"/><Text style={s.label}>{['reunion','ubicacion'].includes(type)?'Fecha preferida':'Celular'}</Text><TextInput style={s.input} placeholder={['reunion','ubicacion'].includes(type)?'DD / MM / AAAA':'+57 300 000 0000'} placeholderTextColor="#98A5AB"/><Button onPress={done}>Enviar solicitud</Button>{type==='contacto'&&<Pressable style={s.whatsapp} onPress={()=>Linking.openURL('https://wa.me/573167560598')}><Ionicons name="logo-whatsapp" size={21} color={C.dark}/><Text style={s.whatsappText}>Continuar por WhatsApp</Text></Pressable>}</View>}</View></Modal>
}

const tabs=[['inicio','Inicio','home-outline','home'],['solicitar','Solicitar','add-circle-outline','add-circle'],['resultados','Resultados','document-text-outline','document-text'],['agenda','Agenda','calendar-outline','calendar'],['perfil','Cuenta','person-outline','person']];
export default function App(){
 const [tab,setTab]=useState('inicio'),[sheet,setSheet]=useState(null);
 const screen=tab==='inicio'?<Home go={setTab} open={setSheet}/>:tab==='solicitar'?<Request open={setSheet}/>:tab==='resultados'?<Results open={setSheet}/>:tab==='beneficios'?<Benefits/>:tab==='agenda'?<Agenda open={setSheet}/>:<Profile open={setSheet}/>;
 return <SafeAreaView style={s.safe}><StatusBar barStyle="dark-content"/><View style={s.app}>{screen}<View style={s.tabs}>{tabs.map(t=><Pressable key={t[0]} onPress={()=>setTab(t[0])} style={s.tab}><Ionicons name={tab===t[0]?t[3]:t[2]} size={23} color={tab===t[0]?C.green:C.muted}/><Text style={[s.tabText,tab===t[0]&&{color:C.dark,fontWeight:'900'}]}>{t[1]}</Text></Pressable>)}</View></View>{sheet&&<Sheet type={sheet} close={()=>setSheet(null)}/>}</SafeAreaView>
}

const s=StyleSheet.create({
 safe:{flex:1,backgroundColor:C.white,paddingTop:Platform.OS==='android'?StatusBar.currentHeight:0},app:{flex:1,backgroundColor:C.bg},screen:{padding:20,paddingBottom:115},header:{flexDirection:'row',justifyContent:'space-between',alignItems:'center',marginBottom:22},brand:{fontSize:11,fontWeight:'900',letterSpacing:1.7,color:C.dark},h1:{fontSize:27,fontWeight:'900',color:C.ink,marginTop:4,letterSpacing:-.5},sub:{fontSize:15,color:C.muted,marginTop:3},icon:{width:42,height:42,borderRadius:21,alignItems:'center',justifyContent:'center',borderWidth:1,borderColor:C.line},between:{flexDirection:'row',alignItems:'center',justifyContent:'space-between'},
 member:{borderRadius:24,padding:20,marginBottom:24,shadowColor:C.navy,shadowOpacity:.18,shadowRadius:16,shadowOffset:{width:0,height:9},elevation:5},memberHead:{flexDirection:'row',alignItems:'center',gap:11},memberIcon:{width:42,height:42,borderRadius:13,backgroundColor:'rgba(70,225,185,.14)',alignItems:'center',justifyContent:'center'},lightOver:{fontSize:10,fontWeight:'900',letterSpacing:1.3,color:'#B9D2D9'},memberTitle:{fontSize:21,fontWeight:'900',color:C.white,marginTop:2},memberCopy:{fontSize:13,lineHeight:19,color:'#D2E2E6',marginTop:17},progress:{height:6,borderRadius:5,backgroundColor:'rgba(255,255,255,.18)',marginTop:12},progressFill:{width:'80%',height:6,borderRadius:5,backgroundColor:'#62E6C0'},lightLink:{color:'#6AE8C5',fontWeight:'900',fontSize:13,marginTop:14},
 pill:{alignSelf:'flex-start',borderRadius:20,paddingHorizontal:9,paddingVertical:6},pillText:{fontSize:9,fontWeight:'900',letterSpacing:.4},section:{fontSize:18,fontWeight:'900',color:C.ink,marginTop:4,marginBottom:12},grid:{flexDirection:'row',flexWrap:'wrap',gap:12,marginBottom:24},quick:{width:'48%',minHeight:139,padding:15,borderRadius:19,backgroundColor:C.white,borderWidth:1,borderColor:C.line},quickIcon:{width:41,height:41,borderRadius:13,alignItems:'center',justifyContent:'center',marginBottom:14},quickTitle:{fontWeight:'900',fontSize:15,color:C.ink},quickCopy:{fontSize:12,color:C.muted,marginTop:4,lineHeight:17},
 card:{backgroundColor:C.white,borderWidth:1,borderColor:C.line,borderRadius:20,padding:18,marginBottom:18},order:{fontSize:10,fontWeight:'800',color:C.muted},visit:{flexDirection:'row',gap:15,alignItems:'center',marginTop:17},date:{width:59,borderRadius:13,backgroundColor:C.navy,alignItems:'center',paddingVertical:8},dateDay:{fontSize:24,fontWeight:'900',color:C.white},dateMonth:{fontSize:9,fontWeight:'900',color:'#62E5BF'},cardTitle:{fontSize:16,fontWeight:'900',color:C.ink,marginBottom:7},meta:{fontSize:12,color:C.muted,marginTop:5},line:{height:1,backgroundColor:C.line,marginVertical:15},prof:{flexDirection:'row',alignItems:'center',gap:10},avatar:{width:42,height:42,borderRadius:21,backgroundColor:C.mint,alignItems:'center',justifyContent:'center'},avatarText:{fontSize:13,fontWeight:'900',color:C.dark},caption:{fontSize:11,color:C.muted,marginTop:3},strong:{fontSize:14,fontWeight:'900',color:C.ink},prep:{flexDirection:'row',gap:9,backgroundColor:C.gold,borderRadius:13,padding:12,marginTop:15},prepText:{flex:1,fontSize:12,lineHeight:17,color:'#715616'},link:{fontSize:13,fontWeight:'900',color:C.dark},eventPreview:{flexDirection:'row',alignItems:'center',gap:13,backgroundColor:C.white,borderRadius:18,borderWidth:1,borderColor:C.line,padding:15},tag:{fontSize:9,fontWeight:'900',letterSpacing:1,color:C.dark},demo:{fontSize:10,lineHeight:15,color:'#87969D',marginTop:10},
 steps:{flexDirection:'row',alignItems:'center',paddingHorizontal:20,marginBottom:20},step:{width:31,height:31,borderRadius:16,backgroundColor:'#E0E9EA',alignItems:'center',justifyContent:'center'},stepActive:{backgroundColor:C.green},stepText:{fontSize:12,fontWeight:'900',color:C.muted},stepLine:{height:2,backgroundColor:C.line,flex:1},search:{height:50,flexDirection:'row',alignItems:'center',backgroundColor:C.white,borderWidth:1,borderColor:C.line,borderRadius:14,paddingHorizontal:14,marginBottom:14},searchInput:{flex:1,fontSize:14,color:C.ink,marginLeft:8},test:{minHeight:66,flexDirection:'row',alignItems:'center',gap:12},topLine:{borderTopWidth:1,borderTopColor:C.line},check:{width:22,height:22,borderRadius:7,borderWidth:2,borderColor:'#B9C8CD',alignItems:'center',justifyContent:'center'},checked:{backgroundColor:C.green,borderColor:C.green},testPrice:{fontSize:13,fontWeight:'900',color:C.ink},quote:{backgroundColor:'#EEFCF8',borderWidth:1,borderColor:'#B9E7DB',borderRadius:18,padding:17,marginBottom:16},rowText:{fontSize:13,color:C.muted,marginBottom:9},rowValue:{fontSize:13,fontWeight:'800',color:C.ink,marginBottom:9},totalLabel:{fontSize:15,fontWeight:'900',color:C.ink},total:{fontSize:21,fontWeight:'900',color:C.dark},button:{minHeight:52,borderRadius:15,backgroundColor:C.green,flexDirection:'row',alignItems:'center',justifyContent:'center',gap:9,paddingHorizontal:18,marginTop:6},buttonOutline:{backgroundColor:C.white,borderWidth:1,borderColor:C.green},buttonText:{fontSize:15,fontWeight:'900',color:C.white},
 result:{backgroundColor:C.white,borderWidth:1,borderColor:C.line,borderRadius:19,padding:17,marginBottom:12},resultTitle:{fontSize:16,fontWeight:'900',color:C.ink,marginTop:15},miniProgress:{height:5,backgroundColor:C.line,borderRadius:4,marginTop:14},miniDone:{width:'66%',height:5,backgroundColor:C.green,borderRadius:4},actionRow:{flexDirection:'row',gap:9},darkButton:{flex:1,height:43,borderRadius:12,backgroundColor:C.navy,flexDirection:'row',alignItems:'center',justifyContent:'center',gap:8},darkText:{color:C.white,fontWeight:'900',fontSize:13},privacy:{flexDirection:'row',alignItems:'center',gap:11,backgroundColor:C.blue,borderRadius:15,padding:14},privacyText:{flex:1,fontSize:12,lineHeight:18,color:'#35617A'},
 segment:{flexDirection:'row',backgroundColor:'#E3ECEC',padding:4,borderRadius:14,marginBottom:17},segmentItem:{flex:1,paddingVertical:10,alignItems:'center',borderRadius:11},segmentActive:{backgroundColor:C.white},segmentText:{fontSize:11,color:C.muted},segmentTextActive:{color:C.navy,fontWeight:'900'},saving:{borderRadius:20,padding:20,marginBottom:22},savingNumber:{fontSize:46,fontWeight:'900',color:'#61E5BF',marginTop:6},savingCopy:{fontSize:13,color:'#D4E4E7'},priceRow:{minHeight:67,flexDirection:'row',alignItems:'center'},basePrice:{fontSize:11,color:C.muted,textDecorationLine:'line-through',marginTop:4},memberPrice:{fontSize:16,fontWeight:'900',color:C.dark},
 filters:{gap:8,paddingBottom:16},filter:{borderWidth:1,borderColor:C.line,borderRadius:20,paddingVertical:8,paddingHorizontal:16,backgroundColor:C.white},filterActive:{backgroundColor:C.navy,borderColor:C.navy},filterText:{fontSize:12,fontWeight:'800',color:C.muted},agenda:{backgroundColor:C.white,borderWidth:1,borderColor:C.line,borderRadius:20,padding:18,marginBottom:13},agendaTitle:{fontSize:18,fontWeight:'900',color:C.ink,marginTop:14},agendaCopy:{fontSize:13,lineHeight:19,color:C.muted,marginVertical:7},reserve:{height:43,backgroundColor:C.mint,borderRadius:12,marginTop:16,flexDirection:'row',alignItems:'center',justifyContent:'center',gap:8},reserveText:{fontSize:13,fontWeight:'900',color:C.dark},
 profileHero:{alignItems:'center',paddingVertical:8,marginBottom:20},bigAvatar:{width:84,height:84,borderRadius:42,backgroundColor:C.mint,alignItems:'center',justifyContent:'center',borderWidth:4,borderColor:C.white},bigAvatarText:{fontSize:24,fontWeight:'900',color:C.dark},profileName:{fontSize:20,fontWeight:'900',color:C.ink,marginTop:12},menu:{minHeight:58,flexDirection:'row',alignItems:'center',gap:13},menuText:{flex:1,fontSize:14,fontWeight:'800',color:C.ink},website:{minHeight:53,borderRadius:15,backgroundColor:C.navy,flexDirection:'row',alignItems:'center',justifyContent:'center',gap:10},websiteText:{fontSize:14,fontWeight:'900',color:C.white},version:{textAlign:'center',fontSize:11,color:C.muted,marginTop:22},
 tabs:{position:'absolute',left:0,right:0,bottom:0,height:Platform.OS==='ios'?88:72,paddingBottom:Platform.OS==='ios'?19:6,backgroundColor:C.white,borderTopWidth:1,borderTopColor:C.line,flexDirection:'row',shadowColor:C.navy,shadowOpacity:.08,shadowRadius:12},tab:{flex:1,alignItems:'center',justifyContent:'center',gap:4},tabText:{fontSize:9,fontWeight:'800',color:C.muted},
 backdrop:{flex:1,backgroundColor:'rgba(10,30,42,.55)'},sheet:{position:'absolute',left:0,right:0,bottom:0,backgroundColor:C.white,borderTopLeftRadius:27,borderTopRightRadius:27,padding:21,paddingBottom:Platform.OS==='ios'?36:22},handle:{width:42,height:5,borderRadius:3,backgroundColor:'#D6E0E2',alignSelf:'center',marginBottom:19},sheetTitle:{fontSize:22,fontWeight:'900',color:C.ink},sheetCopy:{fontSize:13,lineHeight:19,color:C.muted,marginTop:5,paddingRight:16},form:{marginTop:18},label:{fontSize:12,fontWeight:'900',color:C.ink,marginBottom:7},input:{height:49,borderWidth:1,borderColor:C.line,borderRadius:13,paddingHorizontal:13,fontSize:14,color:C.ink,marginBottom:13},whatsapp:{height:50,borderRadius:14,backgroundColor:C.mint,flexDirection:'row',alignItems:'center',justifyContent:'center',gap:8,marginTop:10},whatsappText:{fontSize:14,fontWeight:'900',color:C.dark}
});
